spring:
  config:
    activate:
      on-profile: default, local

  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: production

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379