FROM openjdk:17

ARG INSIDEOUT_DB_URL
ARG INSIDEOUT_DB_USERNAME
ARG INSIDEOUT_DB_PASSWORD
ARG INSIDEOUT_JWT_SECRET_KEY

WORKDIR /app

COPY /api/build/libs/api.jar api.jar

ENV INSIDEOUT_DB_URL=$INSIDEOUT_DB_URL
ENV INSIDEOUT_DB_USERNAME=$INSIDEOUT_DB_USERNAME
ENV INSIDEOUT_DB_PASSWORD=$INSIDEOUT_DB_PASSWORD
ENV INSIDEOUT_JWT_SECRET_KEY=$INSIDEOUT_JWT_SECRET_KEY
ENV SPRING_PROFILES_ACTIVE=production

ENTRYPOINT ["java", "-jar", "api.jar"]
