### 1. 업로드

GET {{baseUrl}}/api/v1/files/presignedUrl/upload?fileName=testFile.txt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiZXhwIjoxNzUwOTAxOTAyfQ.clfMldasIiyPYO35_XF5iNhEO5n3VH9TuV8kVuUECBF1x39PqzLm99pVi7796QwBsSczHOlJ4zz2dK6KFLwXqA
Accept: */*
Connection: keep-alive

### 1. 다운로드

GET {{baseUrl}}/api/v1/files/5/presignedUrl/download
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1IiwiZXhwIjoxNzUwOTAxOTAyfQ.clfMldasIiyPYO35_XF5iNhEO5n3VH9TuV8kVuUECBF1x39PqzLm99pVi7796QwBsSczHOlJ4zz2dK6KFLwXqA
Accept: */*
Connection: keep-alive
