### 2. 헬스체크

GET https://ksy-insideout.com/api/v1/health
Content-Type: application/json
Accept: */*
Connection: keep-alive

### 3. 테스트

GET {{baseUrl}}/api/v1/test
Content-Type: application/json
Accept: */*
Connection: keep-alive