logging:
  level:
    root: info

server:
  port: 8080
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: default, local

  batch:
    job:
      enabled: true  # Batch job 실행을 허용
      name: ${job.name:NONE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insideout
    username: root
    password:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_updates: true
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret-key: test==gslQJkmrazoY1ytKUji6V0Qd49dWiCXxXVFMFQLezNuxEoFTQ7Xl6A1F7piKFybsZnoE06nnvaMbpAbPcKoeBg==

---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${INSIDEOUT_DB_URL}
    username: ${INSIDEOUT_DB_USERNAME}
    password: ${INSIDEOUT_DB_PASSWORD}
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  data:
    redis:
      host: ${INSIDEOUT_REDIS_HOST}
      port: ${INSIDEOUT_REDIS_PORT}

jwt:
  secret-key: ${INSIDEOUT_JWT_SECRET_KEY}
